site_name: Kusk
site_description: 'Make OpenAPI the source of truth for K8s configuration'
site_author: 'Kubeshop Kusk Team'
docs_dir: docs/
repo_name: 'kubeshop/kusk'
repo_url: 'https://github.com/kubeshop/kusk'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  analytics:
    gtag: G-GJSMW2FLG0
  highlightjs: true
  hljs_languages:
    - yaml

nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  - OpenAPI Extension: openapi-extension.md
  - Using with ArgoCD: argocd.md

  - Generators:
    - Ambassador: ambassador.md
    - Linkerd: linkerd.md
    - Nginx-Ingress: nginx-ingress.md

  - For Developers: development.md

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>

